export default function handler(req, res) {
  const educationData = [
    {
      dateStart: "Oct 2021",
      dateEnd: "Completed",
      course: "Systems Design Expert",
      institution: "AlgoExpert.io",
      location: "Remote",
      institutionLogo: "/education/algoexpert-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Oct 2021",
      dateEnd: "Completed",
      course: "Progressive Web Apps - Academind",
      institution: "Udemy",
      location: "Remote",
      institutionLogo: "/education/udemy-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Jan 2019",
      dateEnd: "May 2019",
      course: "Full Stack Web Developer Nanodegree",
      institution: "Udacity",
      location: "Remote, US",
      institutionLogo: "/work/udacity-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Sep 2017",
      dateEnd: "TBA",
      course: "MSc Renewable Energy",
      institution: "University of Jordan",
      location: "Amman, JO",
      institutionLogo: "/education/ju-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Nov 2016",
      dateEnd: "Oct 2017",
      course: "Self Driving Car Engineer Nanodegree",
      institution: "Udacity",
      location: "Remote, US",
      institutionLogo: "/work/udacity-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Jun 2016",
      dateEnd: "Jul 2016",
      course: "Android Basics Nanodegree",
      institution: "Udacity",
      location: "Remote, US",
      institutionLogo: "/work/udacity-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Jan 2010",
      dateEnd: "Dec 2015",
      course: "BEng (Hons) Mechatronics Engineering",
      institution: "UCSI University",
      location: "Kuala Lumpur, MY",
      institutionLogo: "/education/ucsi-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Jan 2010",
      dateEnd: "Dec 2010",
      course: "Science Foundation",
      institution: "UCSI University",
      location: "Kuala Lumpur, MY",
      institutionLogo: "/education/ucsi-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "Sep 2007",
      dateEnd: "May 2008",
      course: "IGCSE/O-Levels",
      institution: "Unity Highschool",
      location: "Khartoum, SD",
      institutionLogo: "/education/uhs-logo.jpg",
      relatedProjects: [],
    },
    {
      dateStart: "completion",
      dateEnd: "60%",
      course: "Algorithms Expert",
      institution: "AlgoExpert.io",
      location: "Remote",
      institutionLogo: "/education/algoexpert-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "completion",
      dateEnd: "25%",
      course: "MongoDB Complete - Academind",
      institution: "Udemy",
      location: "Remote",
      institutionLogo: "/education/udemy-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "completion",
      dateEnd: "15%",
      course: "React Native - Academind",
      institution: "Udemy",
      location: "Remote",
      institutionLogo: "/education/udemy-logo.png",
      relatedProjects: [],
    },
    {
      dateStart: "completion",
      dateEnd: "0%",
      course: "Ionic & Angular - Academind",
      institution: "Udemy",
      location: "Remote",
      institutionLogo: "/education/udemy-logo.png",
      relatedProjects: [],
    },
  ];

  res.status(200).json(educationData);
}
